### ISSUE TITLE
"Refer to Context"

### ISSUE THREAD

**Issue by fernando-torterolo** [InteractiveAdvertisingBureau/openrtb#32]
Question about context field, on Object: Request.

the spec says: object: recomended 

why not is defined as a Object: Context. with this spec, and with a reference "Refer to Context"

 Context
-    site: [Site],
-    app: [App],
-    dooh: [Dooh],
-    user: [User],
-    device: [Device],
-    regs: [Regs],
-    restrictions: [Restrictions]

Layer-4 domain object structure that provides context for the items being offered conforming to the specification and version referenced in openrtb.domainspec and openrtb.domainver.
For AdCOM v1.x, the objects allowed here all of which are optional are one of the DistributionChannel subtypes (i.e., Site, App, or Dooh), User, Device, Regs, Restrictions, and any objects subordinate to these as specified by AdCOM.

https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/OpenRTB%20v3.0%20FINAL.md#object--request-

thanks

**Comment by stemsmit** [comment]
It is odd to not see a link to the [AdCOM Context Spec](https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/master/AdCOM%20v1.0%20FINAL.md#contextobjects) there.

**Comment by wittjill** [comment]
Could you submit a PR with the requested update?
