### ISSUE TITLE
Contradiction in the supply chain object spec

### ISSUE THREAD

**Issue by MacCrazyBean** [InteractiveAdvertisingBureau/openrtb#44]
In the definition of the `nodes` attribute, it says the first node can be the the owner of the site. However, the owner of the site or the publisher doesn't have an `sid` that represents the upstream entity because it's the inventory creator, not the reseller, and the field `sid` is required so how can a node of publisher be included in the supply chain object?

**Comment by iantri** [comment]
Hi MacCrazyBean,

I think its a matter of poor phrasing, and I'll speak to other working group participants to see if we can/should revise. The first node should represent the first a) advertising system the impression passes through and b) the seller ID on that advertising system. 

So, in this phrase:

> In a complete supply chain, the first node represents the initial advertising system and seller ID involved in the transaction, [i.e. the owner of the site, app, or other medium].

The part I've put in brackets should be interpreted as referring to the seller ID only. The initial advertising system that touches the impression would be the one with the direct relationship with the publisher and thus the seller ID would represent that direct relationship with the publisher. 

Makes sense?
