### ISSUE TITLE
SupplyChain Object tamper-prevention

### ISSUE THREAD

**Issue by paavanb** [InteractiveAdvertisingBureau/openrtb#56]
Does the 3.0 specification in any way prevent malicious/unscrupulous sellers from modifying the SupplyChain Object that is passed to downstream demand sources?

The Ads.cert specification allows buyers to cryptographically verify the integrity of the BidRequest object, but it doesn't seem as if any signing of the SupplyChain Object takes place at downstream transactions. What prevents a seller from simply removing SupplyChainNodes from the list and misrepresenting the supply chain to a buyer?

**Comment by emailcurt** [comment]
Your assessment is correct.  DSPs have methods to detect this sometimes, but it is not a solved problem in current specs.

**Comment by paavanb** [comment]
Good to know! Are there any RFC's or open proposals attempting to address this issue?

**Comment by emailcurt** [comment]
Yes there is a somewhat active discussion on this, I believe documented here: https://docs.google.com/document/d/1G2j59nMXybhxtgM1wnPcmQihnINmGj4V6VpgScYcW-o/edit

**Comment by paavanb** [comment]
Fantastic. If I have questions concerning that document, are comments the best way of reaching out?

**Comment by wittjill** [comment]
please reach out to support@iabtechlab.com with any questions
