### ISSUE TITLE
New object for dooh

### ISSUE THREAD

**Issue by roman-jaduda** [InteractiveAdvertisingBureau/openrtb#8]
Wouldn't it be better to introduce a new Object Type for dooh. Currently each SSP is using either site or app. But both are wrong.

Should we introduce something like

```
dooh: {
  player_id: "Some Unique Identifier per SSP",
  name: "Terminal A, Gate 52",
  location: {
    id: "42203".
    name: "Airport Citz XZY
  }, 
  network: {
     id: "3442",
     name: "GDNP Airport"
  }
}
```

If these information are not going into the standard, there should be at least a guidline about how to fill existing app or site object with these data. But I really prefer to add a new dooh type. I think dooh is a bigger evolution to openrtb then app has been to online.

I am open to discuss this. Happy to discuss this with you at Demexo. Just send me a message.

**Comment by drjbutler** [comment]
The "Dooh" object was added as a sibling to "Site" and "App" over in the AdCOM specification.
